version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=carbonleap
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=farm_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./backend
    command: celery -A app.tasks.main.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: