# render.yaml
# Corrected version with 'postgres' type

services:
  # PostgreSQL Database
  - type: postgres # Changed from psql
    name: farm-database
    plan: free
    databaseName: farm_db
    user: carbonleap

  # Redis Instance
  - type: redis
    name: farm-redis
    plan: free

  # Backend API (FastAPI)
  - type: psv
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SQLALCHEMY_DATABASE_URL
        fromService:
          type: postgres # Changed from psql
          name: farm-database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: farm-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: farm-redis
          property: connectionString

  # Celery Background Worker
  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: ./backend/Dockerfile
    startCommand: celery -A app.tasks.main.celery_app worker --loglevel=info
    envVars:
      - key: SQLALCHEMY_DATABASE_URL
        fromService:
          type: postgres # Changed from psql
          name: farm-database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: farm-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: farm-redis
          property: connectionString

  # Frontend (React)
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    healthCheck:
      path: /