# render.yaml
# This file specifies the services to deploy on Render.

services:
  # PostgreSQL Database
  - type: psql
    name: farm-database
    plan: free
    databaseName: farm_db
    user: carbonleap

  # Redis Instance
  - type: redis
    name: farm-redis
    plan: free

  # Backend API (FastAPI) - as a Private Service
  - type: psv
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SQLALCHEMY_DATABASE_URL
        fromService:
          type: psql
          name: farm-database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: farm-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: farm-redis
          property: connectionString

  # Celery Worker - as a Background Worker
  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: ./backend/Dockerfile
    startCommand: celery -A app.tasks.main.celery_app worker --loglevel=info
    envVars:
      - key: SQLALCHEMY_DATABASE_URL
        fromService:
          type: psql
          name: farm-database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: farm-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: farm-redis
          property: connectionString

  # Frontend (React) - as a Static Site for better performance and cost
  - type: static
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    # Render's static sites are served from the 'build' or 'dist' directory
    # We need to tell it where to find the output of `yarn build`
    dockerBuildPath: ./frontend 
    # No start command needed, Render handles serving static files