# render.yaml
# Final version with ipAllowList and removing the worker definition

databases:
  - name: farm-database
    plan: free
    databaseName: farm_db
    user: carbonleap

services:
  # Managed Redis Instance for Celery
  - type: redis
    name: farm-redis
    plan: free
    ipAllowList: [] # Allows access from other services on your Render account

  # Backend API (FastAPI)
  - type: pserv
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SQLALCHEMY_DATABASE_URL
        fromDatabase:
          name: farm-database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: farm-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: farm-redis
          property: connectionString

  # Frontend (React)
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile

  # NOTE: The celery_worker is now defined in docker-compose.yml
  # and will be picked up by the Blueprint.