# render.yaml
# Final corrected version with 'pserv' for the private service type

databases:
  # Managed PostgreSQL Database
  - name: farm-database
    plan: free
    databaseName: farm_db
    user: carbonleap

services:
  # Managed Redis Instance for Celery
  - type: redis
    name: farm-redis
    plan: free

  # Backend API (FastAPI) - as a Private Service
  - type: pserv # Corrected from 'private' to 'pserv'
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SQLALCHEMY_DATABASE_URL
        fromDatabase:
          name: farm-database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: farm-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: farm-redis
          property: connectionString

  # Celery Background Worker
  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: ./backend/Dockerfile
    startCommand: celery -A app.tasks.main.celery_app worker --loglevel=info
    envVars:
      - key: SQLALCHEMY_DATABASE_URL
        fromDatabase:
          name: farm-database
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: farm-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: farm-redis
          property: connectionString

  # Frontend (React)
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    healthCheck:
      path: /